### ISSUE TITLE
Massive log spam when disabling any item type

### ISSUE THREAD

**Issue by ghost** [MehVahdJukaar/WoodGood#147]
Minecraft 1.19.2
Fabric 0.14.17
Every Compat 2.2.2
Game log: https://gist.github.com/Puffadillo/a2279e3232ec0f778187257295a4846f

Hi, I disabled 2 of the wood item types from Every Compat (in order to clean up a pack I'm making) but the mod is throwing massive amounts of errors because of this due to "missing models" (see the game log above.) Even just disabling railings and planter boxes causes over 7,600 lines of errors, and it's causing me considerable lag. A fix would be much appreciated if possible.

**Comment by MehVahdJukaar** [comment]
should be fixed

**Comment by ghost** [comment]
This is mostly fixed in 2.3.1, thanks. I'm still getting some missing texture log spam; although it's not as extreme as 7,600 lines, it's still here to some degree:

`Using missing texture, file everycomp:textures/block/af/betterend/planter_box/tenanea_supports.png not found`

It seems to only be with the planter box from Another Furniture.

**Comment by Xelbayria** [comment]
is it fully fixed in the latest version?

**Comment by Strubbelkopp** [comment]
Definitely still happening on the newest version for 1.20.1:
https://mclo.gs/vJzGStO (line 2280-6689)

Minecraft: 1.20.1
Every Compat: 1.20-2.6.31
Forge: 47.2.20

**Comment by Xelbayria** [comment]
> Hi, I disabled 2 of the wood item types from Every Compat

which wood item types???

**Comment by Strubbelkopp** [comment]
> which wood item types???

It looks like they turned off the planter box from 'Another Furniture' and the railings from 'Architects Pallette'

**Comment by Xelbayria** [comment]
Ok I ran a test on this with the latest version: 
- Every Compat v2.6.34
- Moonlight lib v2.10.3

there is no spam in the log with specific 2 items turned off. 

EDIT:
wrong version. that was 1.20.1. I ran test on 1.19.2 with: 
- Every Compat v2.5.19
- Moonlight Lib v2.3.6

the spam still shows up. I'll see if I can apply the fix from 1.20.1 to 1.19.2

**Comment by Xelbayria** [comment]
Fixed 1.19.2 and will be in the next version
