### ISSUE TITLE
 [🗃]: Making the Workbench from MrCrayFish's Furniture Mod: Refurbished, compatible with modded Woods

### ISSUE THREAD

**Issue by szunakabeats** [MehVahdJukaar/WoodGood#574]
### Version

v1.0.3

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/refurbished-furniture

### Details

When using the workbench, it only shows the vanilla recipes. It would be so nice to put modded woodplanks in it and then see all the craftable furniture from it.

**Comment by Xelbayria** [comment]
I thought it was included. Something changed. Will investigate

**Comment by Xelbayria** [comment]
Fixed in v2.6.70

**Comment by szunakabeats** [comment]
So quick ! Thanks alot :)

**Comment by szunakabeats** [comment]
hmmm for me its still not showing the furniture variants .. 

![image](https://github.com/user-attachments/assets/5258a74e-daed-42f7-a047-40c2b0549c8c)

**Comment by Xelbayria** [comment]
Try get a foreign wood and use the "craftable" mode. so it should show you the blocks from everycomp. I've tested it myself. it's working fine.

If it's not working for you, then i'll need the wood mod (i can test it myself)  


EDIT: 
I've checked the list. They are not sorted. they are at the bottom (end of vanilla) then you'll see the blocks from EveryComp

EDIT 2: 

Here's how I would do it: 
![Furbished_example](https://github.com/user-attachments/assets/d49333e4-6434-4f18-9c89-e4efcd63e953)
