### ISSUE TITLE
[🐞]: EveryCompat causing crash (related to moonlight)

### ISSUE THREAD

**Issue by Gamemassa** [MehVahdJukaar/WoodGood#703]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.21.1 - FABRIC

### EveryCompat Version

everycompat-1.21-2.7.5

### Moonlight Lib Version

moonlight-1.21-2.17.7

### Issue with mods

Not sure.

### Issue Detail

Seems like it's trying to load recipes/assets from mods I don't even have installed.

### OPTIONAL: Latest.log | Crash-report Attachment

Crash Report:
https://mclo.gs/uxdOM3K

Latest.log
https://mclo.gs/7fveNHg

**Comment by Xelbayria** [comment]
I believe the issue is in Moonlight Lib, it has some a few changes related to Recipes. 

try downgrade to older version of Moonlight Lib.

**Comment by Gamemassa** [comment]
> I believe the issue is in Moonlight Lib, it has some a few changes related to Recipes.
> 
> try downgrade to older version of Moonlight Lib.

~What version would you recommend?~ Edit: I tried a handful of different versions. It seems like Moonlight 2.14.X and 2.15.X versions cause crashes on startup, but 2.16.0 is working for now.

**Comment by Xelbayria** [comment]
The bugs in moonlight lib should be fixed. Try the latest version of Moonlight Lib.

**Comment by Gamemassa** [comment]
> The bugs in moonlight lib should be fixed. Try the latest version of Moonlight Lib.

I don't think it's fixed:

Crash Report: https://mclo.gs/QFD6mtg

Latest.log: https://mclo.gs/T8tU8dH

**Comment by MehVahdJukaar** [comment]
your every compat is not updated

**Comment by Gamemassa** [comment]
> your every compat is not updated

With as much respect as possible (because I love your mod and you are a great developer) TF are you talking about?

![image](https://github.com/user-attachments/assets/b306bc11-a059-424a-aa98-ff453a5792ba)


![image](https://github.com/user-attachments/assets/d74c8c15-e05b-4706-8cdf-4b88c0bebf1d)

**Comment by Poopooracoocoo** [comment]
Only on CurseForge for some reason: https://www.curseforge.com/minecraft/mc-mods/every-compat/files/5961351

**Comment by Gamemassa** [comment]
Now I'm getting this crash on startup. Not sure if this is still the same thing or needs its own thread (I did also update Sawmill because that ended up needing to be updated):

Crash Report:
https://mclo.gs/XHxeo0A

Latest.log
https://mclo.gs/HAud6U4

**Comment by Xelbayria** [comment]
Has the **Moonlight Lib v2.17.12** fix the problem?

**Comment by Gamemassa** [comment]
Doesn't seem like it.

Crash Report:
https://mclo.gs/JOhZllB

Latest.log
https://mclo.gs/Zx6tS0v

**Comment by Gamemassa** [comment]
Currently, EveryComp 2.7.5, Moonlight 2.16.0 and Sawmill 1.5.3 are working together in my modpack. If I update Moonlight beyond that, it stops working (and EveryComp 2.7.6 needs Moonlight to also be updated, so by extension that also does not work).

**Comment by Xelbayria** [comment]
It will take some time to find the bug and fix it. I'll check out the crash-report 

**EDIT:**
Oh, something is wrong with **Regions Unexplored Module**, i'll need to look in it

**Comment by Xelbayria** [comment]
@Gamemassa Can you tell me which wood mod is it that caused the Minecraft to crash with EveryComp and Regions Unexplored? 

I'm trying to find out which leavesType has no WoodType.

**EDIT:**
Update EveryComp to v2.8.0 but first backup your world. It has major changes and some bug-fixing

Let me know if that fix the problem or not.

**Comment by Gamemassa** [comment]
I updated EveryComp to 2.8.0 and I'm still getting a crash on startup.

Crash Report:
https://mclo.gs/6T1Tavg

Latest.log
https://mclo.gs/OGTLeS1

**Comment by Xelbayria** [comment]
alright, i need the wood mod to find out what's going on

**Comment by MehVahdJukaar** [comment]
Seems regions unexplored branch blocks aren't checking if a leaf type has a log block

**Comment by Xelbayria** [comment]
> Seems regions unexplored branch blocks aren't checking if a leaf type has a log block

I know. That's why i want to investigate to find out what's going on

**Comment by Gamemassa** [comment]
> Seems regions unexplored branch blocks aren't checking if a leaf type has a log block

Any idea which leaf type in particular?

**Comment by Xelbayria** [comment]
Forgot to close this. It wasn't leaf Type. The block required 2 things: a log and a sapling. 

it was looking at the list via Leaf for wood Types but the list was empty.

**Comment by Xelbayria** [comment]
## FIXED in v2.8.1

**Comment by Poopooracoocoo** [comment]
Seems to be fixed by commit https://github.com/MehVahdJukaar/WoodGood/commit/91d5ed8efb1521613c67f0298138c5e0f23e1d23

**Comment by Xelbayria** [comment]
yup. the file, RegionsUnexploredModule.java. that will explain what was the cause.

**Comment by Gamemassa** [comment]
Yeah, this seems to be fixed, though I am now getting this error message from Roughly Enough Items, which I have reported in their GitHub (and inb4 anyone asks, yes, I also made a new SP world and got the same error message, so it's not just that my old SP world broke).

![image](https://github.com/user-attachments/assets/e1d06754-9edd-458f-8a58-e00727d2b43b)
