### ISSUE TITLE
[🐞]: Fabric Server won't start with some of latest versions of everycompat

### ISSUE THREAD

**Issue by rusteddaemond** [MehVahdJukaar/WoodGood#711]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycomp 1.20-2.7.0 - everycomp 1.20-2.7.2

### Moonlight Lib Version

fabric_1.20-2.13.34 - fabric_1.20-2.13.37

### Issue with mods

Itself and probably moonlight 

### Issue Detail

Server won't start with some of latest versions of everycompat

Same or similar problem was also [on Forge](https://github.com/MehVahdJukaar/WoodGood/issues/710) and still persists on Fabric Server:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'everycomp' at 'net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric'!
```

I was waiting for some time lurking here and there upon issues, yet it wasn't fixed for me:

## FIXED in v2.7.2

_Originally posted by @Xelbayria in https://github.com/MehVahdJukaar/WoodGood/issues/710#issuecomment-2525286802_
            

### OPTIONAL: Latest.log | Crash-report Attachment

Log:
https://mclo.gs/SKrdbxo

No crash, 'koz it wasn't generated.              

### OPTIONAL: To Produce

1. Have Everycompat everycomp 1.20-2.7.0 - everycomp 1.20-2.7.2 
2. Drink Moonshine fabric_1.20-2.13.34 - fabric_1.20-2.13.37
3. Install a couple of wood mods e.g. Biomes You've Gone and Regions Unexplored
4. Install what are there to depend
5. Server doesn't start
6. And it's impossible to stop it, only kill
7. Be be quite frustrated

**Comment by rusteddaemond** [comment]
submitted as separate issue as Fabric /= Forge

**Comment by Xelbayria** [comment]
That's not good. Found this: `java.lang.NoClassDefFoundError: net/minecraft/class_756`

The `#710` is related to renderer class being used on server when it should be excluded. Going to investigate this. 

Have you tried with Furniture mod & Wood mod?

**Comment by rusteddaemond** [comment]
Yes, I've originally started with macaw mods in my full pack, same issue.

**Comment by Xelbayria** [comment]
👌🏻 going to look in this.

**Comment by rusteddaemond** [comment]
> That's not good. Found this: `java.lang.NoClassDefFoundError: net/minecraft/class_756`
> 
> The `#710` is related to renderer class being used on server when it should be excluded. Going to investigate this.
> 
> Have you tried with Furniture mod & Wood mod?


[Here's](https://mclo.gs/1DcrPu4) newest log with Supplementaries and Macaw Furniture.

**Comment by Xelbayria** [comment]
ok that's the same error. Can you check if it generated a crash-report

**Comment by rusteddaemond** [comment]
> ok that's the same error. Can you check if it generated a crash-report

No, sadly it freezes before it could actually start, so, there is no crash report either way.

![{BF017147-F2E5-4BE6-992C-131DE97479F2}](https://github.com/user-attachments/assets/be49a203-988a-4de8-856e-810976bb295a)

**Comment by Xelbayria** [comment]
Freeze? not good. That's another detail I need to know.

**Comment by rusteddaemond** [comment]
> Freeze? not good. That's another detail I need to know.

As I stated in the beginning, it won't start nor stop by itself, you can't manually stop it, only kill.

> 1. Have Everycompat everycomp 1.20-2.7.0 - everycomp 1.20-2.7.2
> 2. Bask in Sunlight fabric_1.20-2.13.34 - fabric_1.20-2.13.37
> 3. Install a couple of wood mods e.g. Biomes You've Gone and Regions Unexplored
> 4. Install what are there to depend
> 5. Server doesn't start
> 6. And it's impossible to stop it, only kill
> 7. Be be quite frustrated

**Comment by yeahpng** [comment]
having this issue as well, although the server just immediately closes for me rather than freezing.

**Comment by Xelbayria** [comment]
## FIXED in v2.7.3

---
cause:
The issue is somewhat related to `#710`, no thanks to Java Class Verifier, the code had to be changed to avoid that "verifier". 🙄

**Comment by rusteddaemond** [comment]
> ## FIXED in v2.7.3
> cause: The issue is somewhat related to `#710`, no thanks to Java Class Verifier, the code had to be changed to avoid that "verifier". 🙄

`[11:25:45] [Server thread/WARN]: Dedicated server took 64.408 seconds to load`

Works for me, many thanks!

**Comment by EtienneWille** [comment]
@Xelbayria It still doesnt works for me but now its a other class issues but still freezes the server on start: 

<details>
<summary>Partially of the log</summary>

`Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'everycomp' at 'net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1087
        at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.lambda$addModules$13(EveryCompatFabric.java:60) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.EveryCompat.addIfLoaded(EveryCompat.java:103) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.addModules(EveryCompatFabric.java:60) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.EveryCompatCommon.initialize(EveryCompatCommon.java:36) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.onInitialize(EveryCompatFabric.java:33) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1087
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.lambda$addModules$13(EveryCompatFabric.java:60) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.EveryCompat.addIfLoaded(EveryCompat.java:103) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.addModules(EveryCompatFabric.java:60) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.EveryCompatCommon.initialize(EveryCompatCommon.java:36) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.onInitialize(EveryCompatFabric.java:33) ~[Every%20Compat%201.20%202.7.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 6 more`

</details>

**Comment by Xelbayria** [comment]
@EtienneWille are you using EveryComp's latest version?

**Comment by EtienneWille** [comment]
@Xelbayria Yes, I am currently using everycomp-1.20-2.7.3-fabric.jar, uploaded on 10.12.2024. With version 2.7.2, I encountered this error: `java.lang.NoClassDefFoundError: net/minecraft/class_756`

Now, with version 2.7.3, I get a different error: `java.lang.NoClassDefFoundError: net/minecraft/class_1087`

The latest version that works for me is 2.6.90, at least from the ones I've tested.

**Comment by Xelbayria** [comment]
@EtienneWille this problem is very troublesome because I honestly don't know why these classes cannot be found. I think it's a problem on FABRIC side, there is no way to confirm that. 

i need the crash-report so i can take a look at what's going on (please create a new issue with the crash-report)
EDIT: Please include which supported mod and which wood mods are you using that caused the crash. thanks

**Comment by EtienneWille** [comment]
@Xelbayria Sadly as the other guy mentioned there is no crash report..

> No, sadly it freezes before it could actually start, so, there is no crash report either way.

**Comment by Xelbayria** [comment]
@EtienneWille Alright, Can i get the list of mods that cause the crash? I am going to try and reproduce it on my side. 

Please create a new issue with the information I need to know. Thanks.
