### ISSUE TITLE
[🐞]: "Could not execute entrypoint stage 'main' due to errors" trying to run Fabric server

### ISSUE THREAD

**Issue by ardunster** [MehVahdJukaar/WoodGood#736]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.8.2-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.12-fabric

### Issue with mods

It has an issue with no other mods besides Fabric API installed.

### Issue Detail

Cannot start Fabric server with this mod installed. It worked fine in my Modrinth single player instance, but when trying to run the server, it fails to start with `java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'everycomp' at 'net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric'`.  If I include just moonlight, the server starts. If I include everycompat, it does not start. 

Running the latest fabric server for 1.21.1: `fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar`
Using Fabric API `fabric-api-0.110.0+1.21.1.jar`

This is the same error in this issue that was closed: https://github.com/MehVahdJukaar/WoodGood/issues/711   but that was for 1.20 so I don't know if it's the same cause.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18234403/latest.log)

**Comment by ardunster** [comment]
In case it's relevant:

```
> java -version
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
```

**Comment by Xelbayria** [comment]
tsk. You can blame Java for that. I'll apply the same fix from 1.20.1 to 1.21.1.

**Comment by ardunster** [comment]
I use Java at work unfortunately, I already blame it for a lot 😂

**Comment by Xelbayria** [comment]
haha. IIRC Class verifier is the culprit that caused the problem. I'll let u know when it's applied.

**Comment by ardunster** [comment]
Great, thanks!

**Comment by Xelbayria** [comment]
## FIXED in v2.8.3 (ported the fix from 1.20.1)

**Comment by Xelbayria** [comment]
If the issue persist with the same error in crash-report. You can re-open this issue.

**Comment by ardunster** [comment]
Thanks! Any idea when I'll see this version on Modrinth? it's still showing 2.8.2 at the moment.

**Comment by Xelbayria** [comment]
I cannot give you the ETA because i am currently working on updating one module that is actually left unfinished. it's missing the recipes stuff 

I'll let u know when it's uploaded.

**Comment by Xelbayria** [comment]
It's uploaded!

**Comment by ardunster** [comment]
Great, thank you so much! Just threw it in the server and confirmed that it starts just fine.

**Comment by Xelbayria** [comment]
👍🏻
