### ISSUE TITLE
[🐞]: Chipped x Every Compat 1.18.2 Stripped Logs

### ISSUE THREAD

**Issue by minerguy341** [MehVahdJukaar/WoodGood#737]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.18.2

### EveryCompat Version

everycomp-1.18.2-1.6.17

### Moonlight Lib Version

selene-1.18.2-1.17.16

### Issue with mods

Chipped-forge-1.18.2-2.0.1
IntegratedDynamics-1.18.2-1.17.5

### Issue Detail

The Chipped Stripped log variants of Menril wood have incorrect ring textures for top and bottom except for "everycomp:ch/integrateddynamics/stripped_menril_log_1", and every consecutive log for 2-16 has mismatched textures for what other woods have for 2-16, and variants 12-16 have full length names instead of "Stripped Menril Log".
![image](https://github.com/user-attachments/assets/26ef8b39-280d-4f98-85ef-3b063e768464)
From left to right: Regular un-chipped Stripped log for Acacia and Menril woods, followed by 1-16 of the Chipped Stripped Wood

**Comment by Xelbayria** [comment]
I need the latest.log, use https://mclo.gs/ to share the latest.log. I have a few guess to why the problem happened.

**Comment by minerguy341** [comment]
https://mclo.gs/vItH9Te

**Comment by Xelbayria** [comment]
## FIXED in Moonlight Lib v1.17.17

**Comment by Xelbayria** [comment]
**NOTE:** You'll need to update Moonlight Lib to v1.17.17 because 2 block of menril's "stripped_log" and "stripped_wood" wasn't detected.

**Comment by minerguy341** [comment]
The names are still broken for block.everycomp.ch.integrateddynamics.stripped_menril_log_12 through 16 (did also update Moonlight)

**Comment by Xelbayria** [comment]
do you mean the title display for these blocks are not correct?

**Comment by minerguy341** [comment]
Yes when you view them in inventory and JADE/WAILA

**Comment by Xelbayria** [comment]
How should they be titled? I'll check

**Comment by minerguy341** [comment]
all of them, if I recall, should just be "Stripped Menril Log" instead of its raw name

**Comment by Xelbayria** [comment]
oh I understand now, "raw name".

**Comment by Xelbayria** [comment]
## FIXED in v1.6.19 - 12 to 16 of stripped_log missing the LANG in en_us

**Comment by Xelbayria** [comment]
Uploaded! 

should be all good now.

**Comment by minerguy341** [comment]
Keep up the amazing modding🎂

**Comment by minerguy341** [comment]
BYG Witch Hazel x Chipped seems to also have incorrect log rings
![image](https://github.com/user-attachments/assets/0fc9e68a-0589-4b1a-909a-0c40f4bcccce)
![image](https://github.com/user-attachments/assets/cb9a6357-b46b-4573-91fd-7472b54baa36)

**Comment by minerguy341** [comment]
Stripped is showing correct rings

**Comment by minerguy341** [comment]
Though this could be because its more visually pleasing

**Comment by Xelbayria** [comment]
Odd. that's not what it looks like on my side when I fixed it. 🤔

**Comment by minerguy341** [comment]
maybe assets need re-generating on my end? Menril seemed fix, could also be an issue with having a lot of mods in general

**Comment by Xelbayria** [comment]
BYG Witch Hazel, right. i'll check on my side.
