### ISSUE TITLE
[🐞]: Missing Textures

### ISSUE THREAD

**Issue by Gyldanword** [MehVahdJukaar/WoodGood#800]
### Code of Conduct

- [x] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycomp-1.20-2.7.15-fabric

### Moonlight Lib Version

moonlight-1.20-2.13.56

### Issue with mods

chipped-fabric-1.20.1-3.0.7
clutter-1.20-0.6.0

### Issue Detail

The textures for the iron barred trapdoors from Chipped are not rendering, nor are the faces of the cupboards from Clutter. Not world-ending, but would be nice to have the options, particularly the cupboards. Thanks for all the hard work! This mod is wonderful! <3

![Image](https://github.com/user-attachments/assets/68099061-9082-4814-a71a-d9de2e4c7eef)
![Image](https://github.com/user-attachments/assets/29f061b9-c524-4823-beed-74c84173004d)

**Comment by Xelbayria** [comment]
ok I am aware of the problem with trapdoor. and Clutter's cupboard. not good. this is currently under investigation. it has to do with the texture not being generated due to some special case. 

EDIT:
do u have BetterEnd installed?  if no, then i need to know which wood mods are these blocks made with.

**Comment by Gyldanword** [comment]
I do not have Better End. I have Biomes O'Plenty (BiomesOPlenty-fabric-1.20.1-13.0.0.94), Let's Do Beachparty (letsdo-beachparty-fabric-1.1.5), Let's Do Vinery (letsdo-vinery-fabric-1.4.28), Let's Do Apple Wood (letsdo-addon-applewood-fabric-1.0.1), Botania (Botania-1.20.1-446-FABRIC), and Monsters & Girls (monsters-girls-fabric-1.20.1-1.2.3). I think that's everything that adds a wood type. There are no modded cupboards from Clutter that render properly. The ones from Farmer's Delight seem just fine. Thank you so much for your time!

**Comment by Xelbayria** [comment]
Alright, Thank you for the information

**Comment by Gyldanword** [comment]
Looking through my modlist more thoroughly, I do also have Wood you Dye (wood_you_dye-1.1.0+1.20.1-fabric). It didn't seem to be interacting with your mod at all, but it does technically add wood types and might interfere, I suppose.

**Comment by Xelbayria** [comment]
That's a different issue. that mean these woodTypes from Wood You Dye weren't detected. The log that get detected has the "bass" sound. 

The present issue has to do with texture generation where it was working fine on FORGE. but not on FABRIC. that's the problem. The issue is complicated.

**Comment by Xelbayria** [comment]
Ok when Moonlight Lib v2.13.58 is out. try it. it should fix the problem

Please let me know if the clutter's cabinet texture is fixed, too

**Comment by Xelbayria** [comment]
## FIXED in Moonlight Lib v2.13.58

**Comment by Gyldanword** [comment]
What a wonderful thing to wake up to! Thank you! <3

**Comment by Gyldanword** [comment]
Well.... Jumping into the game... The cupboards are still the same as the pic I sent. Forgive my hastiness, I literally just woke up, lol.

Taken this morning:

![Image](https://github.com/user-attachments/assets/8b5b7299-fd21-4ca3-8ff7-6078c0e011e9)

**Comment by Gyldanword** [comment]
Just wanted to clarify and give a little more info. I did install the updated Moonlight and the cupboards from Clutter are still showing as above. I did also install Macaw's stuff to give me some options and everything except these Clutter cupboards are working great. In the pic above, you have wood types represented from El & L's Dyes (mint-1.0.5+1.20.1) Arts & Crafts (arts_and_crafts-fabric-1.20.1-1.3.2)(I forgot that those added wood types), Botania, Clutter, Let's Do Beachparty, Let's Do Vinery, Biomes O'Plenty, and Monsters and Girls. Thanks again for your time!

**Comment by Xelbayria** [comment]
👍🏻  alright, i'll investigate and I think clutter may have got a recently update.

**Comment by Xelbayria** [comment]
## FIXED in v2.7.16

--- 
ClutterModule now support Clutter v0.6.0+
