### ISSUE TITLE
[🐞]: BetterNether - Missing Blocks from Macaw's Roofs

### ISSUE THREAD

**Issue by Sansomeness** [MehVahdJukaar/WoodGood#817]
### Code of Conduct

- [x] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycomp-1.20-2.7.16-fabric

### Moonlight Lib Version

moonlight-1.20-2.13.65-fabric

### Issue with mods

BetterNether 9.0.10
Macaw's Roofs 2.3.1

### Issue Detail

Multiple roof blocks are not present in the game at all:

- Stalagnate Roof
- Wart Roof
- Willow Roof
- Nether Reed Roof

And these can be found with EMI, but cannot be found in the creative menu:

- Anchor Tree Steep Top Roof
- Mushroom Fir Steep Top Roof
- Nether Sakura Steep Top Roof
- Rubeus Steep Top Roof
- Stalagnate Steep Top Roof
- Wart Steep Top Roof
- Willow Steep Top Roof
- Nether Reed Steep Top Roof
- Nether Mushroom Steep Top Roof

Note: all of these are log/not-plank variants. The plank roofs appear just fine.

**Comment by Xelbayria** [comment]
Ok found the problem and it's an easy fix. According to the log: 

> [11:46:59] [Render thread/ERROR]: Creative tab cant be null. Found null one for entry set upper_steep_roof

That's why the block wasn't added to creative inventory/menu

**Comment by Xelbayria** [comment]
## FIXED in v2.7.17

**Comment by Sansomeness** [comment]
The steep roofs are now indeed now in the creative menu, thank you for fixing that, but that was only half my issue. The standard roofs for Willow, Stalagnate, Wart, & Nether Reed are still missing from the game entirely.

**Comment by Xelbayria** [comment]
are these `Willow, Stalagnate, Wart, & Nether Reed` woodTypes, if yes, then i need the Ids

**Comment by Sansomeness** [comment]
They are woodTypes. Their Ids are (i think):
betternether:willow
betternether:stalagnate
betternether:wart
betternether:nether_reed

The problem might be that BetterNether adds some roof tile blocks that have similar block ids to what Every Compat would generate.

**Comment by Xelbayria** [comment]
> The problem might be that BetterNether adds some roof tile blocks that have similar block ids to what Every Compat would generate.

I am thinking the same thing. that's why i am checking to see that's possible or not.
