### ISSUE TITLE
The leaf carpets have no name, and some have missing texture color

### ISSUE THREAD

**Issue by 0Navis0** [MehVahdJukaar/WoodGood#84]
The leaf carpets have no id, so it's the full id which displays. Also the textures of willow, palm, mahagony, flowering oak, rainbow birch, coconut have missing texture color. It corresponds to all the leaves which change of color depending of the biomes, or have extra features like flowers or rainbows.

**Comment by MehVahdJukaar** [comment]
should be fixed now

**Comment by 0Navis0** [comment]
The flowering oak and rainbow birch leaf carpet and hedge still don't render correctly.
