### ISSUE TITLE
[🐞]: Armourer's Workshop causes non-vanilla fences/hedges using modded wood/leaf types to break.

### ISSUE THREAD

**Issue by DorkLynx** [MehVahdJukaar/WoodGood#951]
### Code of Conduct

- [x] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.10.7

### Moonlight Lib Version

moonlight-1.21-2.18.16

### Issue with mods

-Armourer's Workshop

### Issue Detail

Armourer's Workshop, when alongside Everycomp + Any modded wall with modded wood/leaves type (i.e.: Macaw's F&W + BOP wood, Macaw's F&W + Chipped leaf types) causes them to break and not connect properly. Wall blocks will connect to regular blocks but not to each other.

![Image](https://github.com/user-attachments/assets/5401d799-c00c-4a46-b623-c21631b76c61)

### OPTIONAL: To Produce

1) Have Everycomp, Chipped, Biomes o' Plenty, and Macaw's fences & walls.
2) Load into a multiplayer server.
3) Place down a Macaw fence type using a modded wood type (i.e.: picket fence with willow wood).
4) Fence/wall/hedge won't connect properly.

**Comment by Xelbayria** [comment]
Can you check these blocks not connecting to see if they have the tag, `#minecraft:wall` for hedges and `#minecraft:fences` for fences IIRC

EDIT: can you reproduce the issue in SIngleplayer (SP) World?  

EDIT 2: please do 👆🏻. I Cannot reproduce the issue on my side. If you got the same issue in SP world. then i'll need the latest.log so i can find out what's causing the EveryCompat to not include these blocks with the tags needed for connecting. 

FYI, `#minecraft:walls` and `#minecraft:fences` are what make these blocks connecting

**Comment by DorkLynx** [comment]
Okay, so I checked the tags -- on singleplayer they show up and work fine, but on servers the tags seem to be missing entirely; I'm not sure what Armourer's Workshop is doing to get rid of the tags on servers specifically.

![Image](https://github.com/user-attachments/assets/cc5a36b6-8aae-4d6a-9964-8d22906dda2e)

![Image](https://github.com/user-attachments/assets/5df5c3f8-d945-4a7d-9c35-bc14847086c6)

**Comment by Xelbayria** [comment]
I see. I'll need the latest.log from Server (use https://mclo.gs/ )... Hopefully, the log can give me some clue to what happened. The only explanation i can think of is something prevent EC's tag generation from starting.

**Comment by DorkLynx** [comment]
[https://mclo.gs/na2H2kM](url)

The server uses a fairly large modpack, but I've tested with solely the mods involved and it still breaks, so I'm fairly sure any of the other mods aren't causing relevant problems. (lmk if I sent the right log..)

**Comment by Xelbayria** [comment]
Haha. you put the URL as NAME in `[NAME](URL)` and the URL is actually leading me to to WoodGood's issue via github. XD  i had to copy the NAME and paste it in the... yeah 

EDIT: 
I took a look at the log. There are no clues. Alas! You'll need to disable each mod at a time until you no longer have the issue. One of the mods must have caused the problem. If you ran out of mods to disable. Let me know.

**Comment by DorkLynx** [comment]
Whoops! My bad haha
I technically already know the culprit mod (Armourer's Workshop) sorry if I wasn't clear enough in my first post; I had set up a server with only Woodgood, Armourer's Workshop, chipped, macaws fences, and BoP to test out the problem and it ONLY breaks if Armourer's Workshop is on there -- In fact, it breaks *several* types of tagged blocks as long as its using everycompact as a base (fences, Beautify's lattices, etc..)

Removing Armourer's Workshop fixes the issue but it's a major part of the modpack so I've been doing a lot of hairpulling till' i remembered there was a github :P

Anything else I should share?

**Comment by Xelbayria** [comment]
> Removing Armourer's Workshop fixes the issue but it's a major part of the modpack so I've been doing a lot of hairpulling till' i remembered there was a github

U ran this on SERVER side? by removing Armourer's Workshop, the problem is fixed? You should contact the DEV of that mod and discuss with the DEV about this problem.  

I would like you to share the latest.log without the mod (Armourer's Workshop) installed. i am going to compare it with the other log you provided above.

**Comment by DorkLynx** [comment]
I made a new blank world to get both latest logs with and without Armourer's workshop to avoid corruption issues on the world i was using, I hope it's sufficient as the bug still persists this way. I'm not sure how or why Armourer's Workshop causes ECs tags to just break?

(Startup Crash) With Armourer's Workshop, first attempt to load server: [Log](https://mclo.gs/sfkAdWM)
With Armourer's Workshop: [Log](https://mclo.gs/FnwHWD9)
Without Armourer's Workshop: [Log](https://mclo.gs/b3StgZb)

**Comment by Xelbayria** [comment]
hmm. Can you try re-login the world a second time with Armourer's Workshop and see if the tags are on blocks' for EC? 

There is no errors for EC's tags. I think they were generated just fine but not loaded first time into the world. 

if you don't want to re-login, then try run a command `/reload` which is Minecraft's one of commands. it should reload tags and recipes. 

if the EC's tags doesn't show up on blocks, then let me know and contact the DEV to get some details. i'm not sure why EC's tags is not showing up on SERVER but it was fine in SP world.

**Comment by MehVahdJukaar** [comment]
Try with just those mods on

**Comment by DorkLynx** [comment]
> if you don't want to re-login, then try run a command `/reload` which is Minecraft's one of commands. it should reload tags and recipes.

..Turns out `/reload` fixed the entire problem! I don't know whether to laugh or cry.
Count it as fixed, but if you want/need anymore info lmk :)

**Comment by Xelbayria** [comment]
I knew it. I've seen this issue before. A few codes was added to EC or SZ (StoneZone) to ensure that tags get loaded first time into the world on either CLIENT or SERVER. This way, no body have to quit the world and re-enter the world a second time to get the tags loaded. or use `/reload`.

Apparently, The code don't work on SERVER. 🤔 

@MehVahdJukaar 

Do you have any idea why it doesn't work on SERVER?
